services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    restart: always
    environment:
      TZ: America/Sao_Paulo
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user"]
      interval: 10s
      timeout: 5s
      retries: 5
 
  web:
    build: .
    working_dir: /app
    container_name: web
    ports:
      - 3000:3000
    command: bash -c "rm -f tmp/pids/server.pid && bin/setup && rails s -b 0.0.0.0"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
 
volumes:
  database:
  rubygems: